language: android

jdk: oraclejdk8

sudo: true

env:
  global:
  - ANDROID_API_LEVEL=23
  - ANDROID_BUILD_TOOLS_VERSION=23.0.1
  - ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL

before_install:
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL,sys-img-x86_64-android-$ANDROID_API_LEVEL
  - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./travis/wait_for_emulator
  - adb shell input keyevent 82 &